# Dockerfile.server
FROM gcc:latest

WORKDIR /app

# 拷贝服务器代码
COPY server.cpp .

# 安装依赖
RUN apt-get update && apt-get install -y \
    libboost-all-dev \
    cmake \
    && rm -rf /var/lib/apt/lists/* || apt-get update

# 安装 nlohmann/json
RUN git clone https://github.com/nlohmann/json.git && cd json && mkdir build && cd build && cmake .. && make install

# 编译服务器代码
RUN g++ -o server server.cpp -lboost_system -lpthread

CMD ["./server"]
